theme: jekyll-theme-architect
title: Diogo Ribeiro
site_name: Diogo Ribeiro
description: Postdoctoral researcher in Bioinformatics
email: diogo.am.ribeiro@gmail.com
header_pages:
  - about.md
twitter_username: jekyllrb
github_username:  jekyll

exclude: ["README.md"]