theme: jekyll-theme-architect
title: Diogo Ribeiro
site_name: Diogo Ribeiro
author: Diogo Ribeiro
description: Postdoctoral researcher in Bioinformatics
email: diogo.am.ribeiro@gmail.com
twitter_username: Diogo_M_Ribeiro
twitter_user: Diogo_M_Ribeiro
twitter_tweet_button: true
google_analytics: UA-186255553-1

exclude: ["README.md"]