theme: jekyll-theme-architect
title: Diogo Ribeiro
site_name: Diogo Ribeiro
description: Postdoctoral researcher in Bioinformatics. [Department of Computational Biology](https://www.unil.ch/dbc/en/home.html), University of Lausanne
email: diogo.am.ribeiro@gmail.com
header_pages:
  - about.md
social_links:
    twitter: jekyllrb
    github: jekyll
